# Generated by Django 4.2.1 on 2023-06-08 18:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainEscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.unique_code_generator, max_length=15, unique=True)),
                ('whoareyou', models.CharField(default='', max_length=48)),
                ('product', models.CharField(default='', max_length=64)),
                ('descript', models.CharField(default='', max_length=256)),
                ('trouble', models.CharField(default='', max_length=256)),
                ('target', models.CharField(default='', max_length=256)),
                ('channel', models.CharField(default='', max_length=48)),
                ('feedback', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
