# Generated by Django 4.2.1 on 2023-06-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_painescale_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painescale',
            name='session',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
